export const MOCK_GIGS = [
  {
    _id: "m1",
    userId: "u1",
    title: "I will build responsive react js, next js website frontend development",
    desc: "I will build you an amazing website using React and Node.",
    cat: "Website Development",
    price: 4000,
    cover: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=800",
    sales: 124,
    rating: 5.0,
    reviewCount: "1k+",
    sellerName: "TechPro Studio",
    sellerImg: "https://i.pravatar.cc/150?u=techpro",
    sellerLevel: "Top Rated Seller"
  },
  {
    _id: "m2",
    userId: "u2",
    title: "I will create a stunning custom website using MERN stack",
    desc: "Full stack web development services tailored to your needs.",
    cat: "Website Development",
    price: 12000,
    cover: "https://images.pexels.com/photos/163140/technology-computer-motherboard-chips-163140.jpeg?auto=compress&cs=tinysrgb&w=800",
    sales: 89,
    rating: 4.9,
    reviewCount: "820",
    sellerName: "DevMasters",
    sellerImg: "https://i.pravatar.cc/150?u=devmasters",
    sellerLevel: "Level 2"
  },
  {
    _id: "m3",
    userId: "u3",
    title: "I will design and develop a high-converting Shopify store",
    desc: "High converting ecommerce stores.",
    cat: "Website Development",
    price: 8500,
    cover: "https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=800",
    sales: 45,
    rating: 5.0,
    reviewCount: "542",
    sellerName: "EcomNinja",
    sellerImg: "https://i.pravatar.cc/150?u=ecomninja",
    sellerLevel: "Pro Seller"
  },
  {
    _id: "m4",
    userId: "u4",
    title: "I will build lightning fast web apps with Vue and Nuxt",
    desc: "Vue expert.",
    cat: "Website Development",
    price: 6000,
    cover: "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=800",
    sales: 210,
    rating: 4.8,
    reviewCount: "2k+",
    sellerName: "VueVanguard",
    sellerImg: "https://i.pravatar.cc/150?u=vuevanguard",
    sellerLevel: "Level 1"
  },
  {
    _id: "m5",
    userId: "u5",
    title: "I will fix bugs and issues in your html css js React website",
    desc: "Fixing bugs and layout completely.",
    cat: "Website Development",
    price: 1500,
    cover: "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=800",
    sales: 430,
    rating: 4.9,
    reviewCount: "950",
    sellerName: "BugSquasher",
    sellerImg: "https://i.pravatar.cc/150?u=bugsquasher",
    sellerLevel: "Level 2"
  },
  {
    _id: "m6",
    userId: "u6",
    title: "I will design and develop an amazing webflow website",
    desc: "Design UI UX on figma to Webflow.",
    cat: "Website Development",
    price: 9000,
    cover: "https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=800",
    sales: 110,
    rating: 5.0,
    reviewCount: "135",
    sellerName: "WebflowWizard",
    sellerImg: "https://i.pravatar.cc/150?u=webflowwiz",
    sellerLevel: "Pro Seller"
  },
  {
    _id: "m7",
    userId: "u7",
    title: "I will build a completely customized WordPress website",
    desc: "Wordpress blog, portfolio and more.",
    cat: "Website Development",
    price: 5000,
    cover: "https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=800",
    sales: 320,
    rating: 4.9,
    reviewCount: "1.2k",
    sellerName: "WP Guru",
    sellerImg: "https://i.pravatar.cc/150?u=wpguru",
    sellerLevel: "Top Rated Seller"
  },
  {
    _id: "m8",
    userId: "u8",
    title: "I will provide complete SEO optimized wix website design",
    desc: "Wix web designer and developer.",
    cat: "Website Development",
    price: 4500,
    cover: "https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=800",
    sales: 78,
    rating: 4.7,
    reviewCount: "94",
    sellerName: "DesignGenius",
    sellerImg: "https://i.pravatar.cc/150?u=designgenius",
    sellerLevel: "Level 1"
  }
];
